export interface BlogPost {
  id: number;
  title: string;
  author: string;
  date: string;
  excerpt: string;
  image: string;
  tags: string[];
  featured?: boolean;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Boost Cancer: What You Need to Know",
    author: "Olivia Myers",
    date: "28 Jan 2025",
    excerpt: "How do you create compelling presentations that wow your colleagues and impress your managers?",
    image: "/images/blog/medical-team.png",
    tags: ["Medical", "Research", "Health"],
    featured: true,
  },
  {
    id: 2,
    title: "Migrating to Linear 101",
    author: "Phoenix Baker",
    date: "19 Jan 2025",
    excerpt: "Linear helps streamline software projects, sprints, tasks, and bug tracking. Here's how to get started.",
    image: "/images/blog/blog-1.png",
    tags: ["Product", "Tech", "Saas"],
  },
  {
    id: 3,
    title: "Building your AI stack",
    author: "Lana Steiner",
    date: "18 Jan 2025",
    excerpt: "The rise of AI/SaaS APIs has been met by a rise in tooling, testing, and managing them.",
    image: "/images/blog/blog-2.png",
    tags: ["Software Development", "AI"],
  },
  {
    id: 4,
    title: "Bill Watch-leadership lessons",
    author: "Alex Whitten",
    date: "17 Jan 2025",
    excerpt: "Like to know the secrets of influencing a 2-14 team size in a Super Bowl winning dynasty?",
    image: "/images/blog/blog-3.png",
    tags: ["Leadership", "Training"],
  },
  {
    id: 5,
    title: "PM mental models",
    author: "Demi Wilkinson",
    date: "16 Jan 2025",
    excerpt: "Mental models are simple expressions of complex processes or relationships.",
    image: "/images/blog/blog-4.png",
    tags: ["Product", "Research", "Frameworks"],
  },
  {
    id: 6,
    title: "How collaboration makes us better designers",
    author: "Karol Craig",
    date: "14 Jan 2025",
    excerpt: "Collaboration can makes us better at teams stronger, and our work better.",
    image: "/images/blog/blog-5.png",
    tags: ["Design", "Research"],
  },
  {
    id: 7,
    title: "Understanding Modern Healthcare Technology",
    author: "Sarah Johnson",
    date: "13 Jan 2025",
    excerpt: "Exploring the latest innovations in healthcare technology and their impact on patient care.",
    image: "/images/blog/blog-1.png",
    tags: ["Healthcare", "Technology", "Innovation"],
  },
  {
    id: 8,
    title: "The Future of Telemedicine",
    author: "Michael Chen",
    date: "12 Jan 2025",
    excerpt: "How telemedicine is revolutionizing healthcare delivery and patient accessibility.",
    image: "/images/blog/blog-2.png",
    tags: ["Telemedicine", "Healthcare", "Digital"],
  },
  {
    id: 9,
    title: "Medical Research Breakthroughs 2025",
    author: "Emily Rodriguez",
    date: "11 Jan 2025",
    excerpt: "A comprehensive overview of the most significant medical research discoveries this year.",
    image: "/images/blog/blog-3.png",
    tags: ["Research", "Medical", "Science"],
  },
  {
    id: 10,
    title: "Patient Care Best Practices",
    author: "David Thompson",
    date: "10 Jan 2025",
    excerpt: "Essential strategies for delivering exceptional patient care in modern healthcare settings.",
    image: "/images/blog/blog-4.png",
    tags: ["Patient Care", "Healthcare", "Best Practices"],
  },
  {
    id: 11,
    title: "Digital Health Records Management",
    author: "Lisa Anderson",
    date: "9 Jan 2025",
    excerpt: "Best practices for managing and securing digital health records in healthcare facilities.",
    image: "/images/blog/blog-5.png",
    tags: ["Health Records", "Digital", "Security"],
  },
  {
    id: 12,
    title: "Healthcare Staffing Solutions",
    author: "Robert Martinez",
    date: "8 Jan 2025",
    excerpt: "Innovative approaches to healthcare staffing and workforce management.",
    image: "/images/blog/blog-1.png",
    tags: ["Staffing", "Healthcare", "Workforce"],
  },
  {
    id: 13,
    title: "Mental Health in Healthcare",
    author: "Jennifer Lee",
    date: "7 Jan 2025",
    excerpt: "Addressing mental health challenges in healthcare professionals and patients.",
    image: "/images/blog/blog-2.png",
    tags: ["Mental Health", "Healthcare", "Wellness"],
  },
  {
    id: 14,
    title: "Preventive Medicine Strategies",
    author: "Christopher Brown",
    date: "6 Jan 2025",
    excerpt: "Effective preventive medicine approaches to improve patient outcomes.",
    image: "/images/blog/blog-3.png",
    tags: ["Preventive Medicine", "Health", "Wellness"],
  },
  {
    id: 15,
    title: "Healthcare Data Analytics",
    author: "Amanda White",
    date: "5 Jan 2025",
    excerpt: "Leveraging data analytics to improve healthcare delivery and patient outcomes.",
    image: "/images/blog/blog-4.png",
    tags: ["Analytics", "Data", "Healthcare"],
  },
  {
    id: 16,
    title: "Emergency Medicine Protocols",
    author: "James Wilson",
    date: "4 Jan 2025",
    excerpt: "Essential protocols and procedures for emergency medical situations.",
    image: "/images/blog/blog-5.png",
    tags: ["Emergency Medicine", "Protocols", "Healthcare"],
  },
  {
    id: 17,
    title: "Healthcare Quality Improvement",
    author: "Patricia Davis",
    date: "3 Jan 2025",
    excerpt: "Strategies for continuous quality improvement in healthcare organizations.",
    image: "/images/blog/blog-1.png",
    tags: ["Quality", "Healthcare", "Improvement"],
  },
  {
    id: 18,
    title: "Medical Device Innovation",
    author: "Mark Taylor",
    date: "2 Jan 2025",
    excerpt: "Exploring the latest innovations in medical devices and their clinical applications.",
    image: "/images/blog/blog-2.png",
    tags: ["Medical Devices", "Innovation", "Healthcare"],
  },
  {
    id: 19,
    title: "Healthcare Policy Updates",
    author: "Nancy Garcia",
    date: "1 Jan 2025",
    excerpt: "Recent updates and changes in healthcare policy and regulations.",
    image: "/images/blog/blog-3.png",
    tags: ["Policy", "Healthcare", "Regulations"],
  },
  {
    id: 20,
    title: "Patient Safety Initiatives",
    author: "Kevin Moore",
    date: "31 Dec 2024",
    excerpt: "Comprehensive approaches to enhancing patient safety in healthcare facilities.",
    image: "/images/blog/blog-4.png",
    tags: ["Patient Safety", "Healthcare", "Quality"],
  },
];

