import { type Job } from "./job-card";

export const JOBS: Job[] = [
  {
    id: 1,
    title: "Accountant",
    company: "University Health Network",
    location: "Toronto, ON",
    type: "Fulltime",
    mode: "Onsite",
    salary: "$80K - $95K CAD",
    experience: "3-5 Years",
    postedAt: "2 Hours Ago",
  },
  {
    id: 2,
    title: "Staff Manager",
    company: "Maple",
    location: "Remote, Canada",
    type: "Fulltime",
    mode: "Remote",
    salary: "$110K - $130K CAD",
    experience: "5-7 Years",
    postedAt: "4 Hours Ago",
  },
  {
    id: 3,
    title: "Staff Manager",
    company: "University Health Network",
    location: "Toronto, ON",
    type: "Fulltime",
    mode: "Onsite",
    salary: "$80K - $95K CAD",
    experience: "3-5 Years",
    postedAt: "2 Hours Ago",
  },
  {
    id: 4,
    title: "Staff Manager",
    company: "Maple",
    location: "Remote, Canada",
    type: "Fulltime",
    mode: "Remote",
    salary: "$110K - $130K CAD",
    experience: "5-7 Years",
    postedAt: "4 Hours Ago",
  },
  {
    id: 5,
    title: "Staff Manager",
    company: "University Health Network",
    location: "Toronto, ON",
    type: "Fulltime",
    mode: "Onsite",
    salary: "$80K - $95K CAD",
    experience: "3-5 Years",
    postedAt: "2 Hours Ago",
  },
  {
    id: 6,
    title: "Accountant",
    company: "Maple",
    location: "Remote, Canada",
    type: "Fulltime",
    mode: "Remote",
    salary: "$110K - $130K CAD",
    experience: "5-7 Years",
    postedAt: "4 Hours Ago",
  },
  {
    id: 7,
    title: "Accountant",
    company: "University Health Network",
    location: "Toronto, ON",
    type: "Fulltime",
    mode: "Onsite",
    salary: "$80K - $95K CAD",
    experience: "3-5 Years",
    postedAt: "2 Hours Ago",
  },
  {
    id: 8,
    title: "Staff Manager",
    company: "Maple",
    location: "Remote, Canada",
    type: "Fulltime",
    mode: "Remote",
    salary: "$110K - $130K CAD",
    experience: "5-7 Years",
    postedAt: "4 Hours Ago",
  },
];

export const ITEMS_PER_PAGE = 8;

